{{- $values := include "anycableGo.values" . | fromYaml }}
{{- with $values.ingress }}
{{- if .enable | and (.acme | default dict).hosts }}
{{- $apiVersion := include "anycableGo.apiVersions.ingress" $ }}
---
apiVersion: {{ $apiVersion }}
kind: Ingress
metadata:
  name: "{{ template "anycableGo.fullname" $ }}-acme"
  annotations:
    kubernetes.io/tls-acme: "true"
    {{- range $key, $value := .annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  {{- if and (semverCompare ">=18" $.Capabilities.KubeVersion.Minor) (.ingressClassName) }}
  ingressClassName: {{ .ingressClassName }}
  {{- end }}
  tls:
    - hosts:
        {{- range $host := .acme.hosts }}
        - {{ $host | quote }}
        {{- end }}
      secretName: "{{ template "anycableGo.fullname" $ }}-tls-acme"
  rules:
    {{- range $host := .acme.hosts }}
    {{- $serviceName := include "anycableGo.fullname" $ }}
    - host: {{ $host | quote }}
      http:
        paths:
          {{- if eq $apiVersion "networking.k8s.io/v1" }}
          - path: {{ .path | quote }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $serviceName | quote }}
                port:
                  name: http
          {{- else }}
          - path: {{ .path | quote }}
            backend:
              serviceName: {{ $serviceName | quote }}
              servicePort: http
          {{- end }}
    {{- end }}
{{- end }}
{{- end }}
